//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATNET_DESKTOP_KON0355_STOCKMETALPRICES.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATNET_DESKTOP_KON0355_STOCKMETALPRICES.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Currency not supported! .
        /// </summary>
        internal static string ApiClientCurrencyErrorMessage {
            get {
                return ResourceManager.GetString("ApiClientCurrencyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Invalid request!.
        /// </summary>
        internal static string ApiClientInvalidRequestErrorMessage {
            get {
                return ResourceManager.GetString("ApiClientInvalidRequestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Metal not suported! .
        /// </summary>
        internal static string ApiClientMetalErrorMessage {
            get {
                return ResourceManager.GetString("ApiClientMetalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Response status is not valid! .
        /// </summary>
        internal static string ApiClientResponseErrorMessage {
            get {
                return ResourceManager.GetString("ApiClientResponseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný https://www.goldapi.io/api/status.
        /// </summary>
        internal static string ApiStatusUrl {
            get {
                return ResourceManager.GetString("ApiStatusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný https://www.goldapi.io/api/.
        /// </summary>
        internal static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný application/json.
        /// </summary>
        internal static string Content_type {
            get {
                return ResourceManager.GetString("Content-type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný CZK.
        /// </summary>
        internal static string CzkMarking {
            get {
                return ResourceManager.GetString("CzkMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Exceptions.
        /// </summary>
        internal static string DefaultExceptionFolderName {
            get {
                return ResourceManager.GetString("DefaultExceptionFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Properties.Resources.
        /// </summary>
        internal static string DefaultResourceFileName {
            get {
                return ResourceManager.GetString("DefaultResourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný EUR.
        /// </summary>
        internal static string EurMarking {
            get {
                return ResourceManager.GetString("EurMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný GBP.
        /// </summary>
        internal static string GbpMarking {
            get {
                return ResourceManager.GetString("GbpMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný XAU.
        /// </summary>
        internal static string GoldMarking {
            get {
                return ResourceManager.GetString("GoldMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný GetJsonDataDict.
        /// </summary>
        internal static string IPluginCoreMethodName {
            get {
                return ResourceManager.GetString("IPluginCoreMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný XPD.
        /// </summary>
        internal static string PalladiumMarking {
            get {
                return ResourceManager.GetString("PalladiumMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný XPT.
        /// </summary>
        internal static string PlatinumMarking {
            get {
                return ResourceManager.GetString("PlatinumMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Data were sucessfully writen to .
        /// </summary>
        internal static string PluginInvokerEventMessage {
            get {
                return ResourceManager.GetString("PluginInvokerEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný  finished its job and was closed..
        /// </summary>
        internal static string PluginInvokerThreadEndMessage {
            get {
                return ResourceManager.GetString("PluginInvokerThreadEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný  created and started to working as main plugin thread..
        /// </summary>
        internal static string PluginInvokerThreadStartMessage {
            get {
                return ResourceManager.GetString("PluginInvokerThreadStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Invalid plugin found! Skipping .
        /// </summary>
        internal static string PluginLoaderErrorMessage {
            get {
                return ResourceManager.GetString("PluginLoaderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Found exception class! Skipping .
        /// </summary>
        internal static string PluginLoaderExceptionClassSkippedMessage {
            get {
                return ResourceManager.GetString("PluginLoaderExceptionClassSkippedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Found resource file! Skipping .
        /// </summary>
        internal static string PluginLoaderResourceFileSkipperMessage {
            get {
                return ResourceManager.GetString("PluginLoaderResourceFileSkipperMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Plugin loaded sucesfully. .
        /// </summary>
        internal static string PluginLoaderSuccesMessage {
            get {
                return ResourceManager.GetString("PluginLoaderSuccesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný \Plugins.
        /// </summary>
        internal static string PluginsDirectoryPath {
            get {
                return ResourceManager.GetString("PluginsDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný *.dll.
        /// </summary>
        internal static string PluginsSuffix {
            get {
                return ResourceManager.GetString("PluginsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný XAG.
        /// </summary>
        internal static string SilverMarking {
            get {
                return ResourceManager.GetString("SilverMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný USD.
        /// </summary>
        internal static string UsdMarking {
            get {
                return ResourceManager.GetString("UsdMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný goldapi-f3o3yhukj8fr6ew-io.
        /// </summary>
        internal static string X_access_token {
            get {
                return ResourceManager.GetString("X-access-token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný \Xml\.
        /// </summary>
        internal static string XmlDirectoryName {
            get {
                return ResourceManager.GetString("XmlDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný .xml.
        /// </summary>
        internal static string XmlSuffix {
            get {
                return ResourceManager.GetString("XmlSuffix", resourceCulture);
            }
        }
    }
}
